---
functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Сайт должен быть доступен на различных устройствах
  -Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Стабильная работа корзины 
  - Безопасные платежные транзакции
  - Интуитивно понятная навигация
  - Адаптивный дизайн
  - Уведомления о статусе заказа
  - Отображение рейтинга товаров
